### ISSUE TITLE
There is nothing custom about this switch 

### ISSUE THREAD

**Issue by adamdahan** [sashamyshkina/UISwitch-tint-background-in-iOS-13#1]
Your documentation is misleading. All you are doing here is changing the background color of the switchs subviews but there is no custom switch requirement. 

Thank you for the repo anyways :)

**Comment by sashamyshkina** [comment]
Hi, Adam! I never meant this to be custom switch. I said I only change subview's color.

"To change tint color in OFF state of UISwitch you need to create a custom class. Or change subviews' color, which is much more EASIER SOLUTION. This small project contains THIS SOLUTION."
Kind regards :)
